apiVersion: v1
kind: Service
metadata:
  name: {{ include "trading-floor.fullname" . }}-api
  labels:
    {{- include "trading-floor.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "trading-floor.selectorLabels" (dict "component" "app" "Release" .Release "Chart" .Chart) | nindent 4 }}
